---  
- name: "Read list of files with incorrect permissions"
  shell: "rpm -Va --nofiledigest | awk '{ if (substr($0,2,1)==\"M\") print $NF }'"
  args:
    warn: False # Ignore ANSIBLE0006, we can't fetch files with incorrect permissions using rpm module
  register: files_with_incorrect_permissions
  failed_when: False
  changed_when: False
  check_mode: no
  tags:
    - rpm_verify_permissions
    - high_severity
    - restrict_strategy
    - high_complexity
    - medium_disruption
    - CCE-27209-6
    - NIST-800-53-AC-6
    - NIST-800-53-AU-9(1)
    - NIST-800-53-AU-9(3)
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - PCI-DSS-Req-11.5
    - CJIS-5.10.4.1
    - DISA-STIG-RHEL-07-010010


- name: "Correct file permissions with RPM"
  shell: "rpm --setperms $(rpm -qf '{{ item }}')"
  args:
    warn: False # Ignore ANSIBLE0006, we can't correct permissions using rpm module
  with_items: "{{ files_with_incorrect_permissions.stdout_lines }}"
  when: (files_with_incorrect_permissions.stdout_lines | length > 0) and True
  tags:
    - rpm_verify_permissions
    - high_severity
    - restrict_strategy
    - high_complexity
    - medium_disruption
    - CCE-27209-6
    - NIST-800-53-AC-6
    - NIST-800-53-AU-9(1)
    - NIST-800-53-AU-9(3)
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - PCI-DSS-Req-11.5
    - CJIS-5.10.4.1
    - DISA-STIG-RHEL-07-010010

- name: "Read list of files with incorrect ownership"
  shell: "rpm -Va --nofiledigest | awk '{ if (substr($0,6,1)==\"U\" || substr($0,7,1)==\"G\") print $NF }'"
  args:
    warn: False # Ignore ANSIBLE0006, we can't fetch files with incorrect ownership using rpm module
  register: files_with_incorrect_ownership
  failed_when: False
  changed_when: False
  check_mode: no
  tags:
    - rpm_verify_ownership
    - high_severity
    - restrict_strategy
    - high_complexity
    - medium_disruption
    - CCE-80545-7
    - NIST-800-53-AC-6
    - NIST-800-53-AU-9(1)
    - NIST-800-53-AU-9(3)
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - PCI-DSS-Req-11.5
    - CJIS-5.10.4.1


- name: Create list of uniq packages
  shell: "rpm -qf {{ files_with_incorrect_ownership.stdout_lines }}|sort |uniq"
  args:
    warn: False # Ignore ANSIBLE0006, we can't fetch packages with files with incorrect ownership using rpm module
  register: uniq_list_of_packages
  when: (files_with_incorrect_ownership.stdout_lines | length > 0) and True
  tags:
    - rpm_verify_ownership
    - high_severity
    - restrict_strategy
    - high_complexity
    - medium_disruption
    - CCE-80545-7
    - NIST-800-53-AC-6
    - NIST-800-53-AU-9(1)
    - NIST-800-53-AU-9(3)
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - PCI-DSS-Req-11.5
    - CJIS-5.10.4.1

- name: "Correct file ownership with RPM"
  shell: "rpm --quiet --setugids '{{ item }}'"
  args:
    warn: False # Ignore ANSIBLE0006, we can't correct ownership using rpm module
  with_items: "{{ uniq_list_of_packages.stdout_lines }}"
  when: (files_with_incorrect_ownership.stdout_lines | length > 0) and True
  tags:
    - rpm_verify_ownership
    - high_severity
    - restrict_strategy
    - high_complexity
    - medium_disruption
    - CCE-80545-7
    - NIST-800-53-AC-6
    - NIST-800-53-AU-9(1)
    - NIST-800-53-AU-9(3)
    - NIST-800-53-CM-6(d)
    - NIST-800-53-CM-6(3)
    - NIST-800-171-3.3.8
    - NIST-800-171-3.4.1
    - PCI-DSS-Req-11.5
    - CJIS-5.10.4.1
